### ISSUE TITLE
release 0.1.0?

### ISSUE THREAD

**Issue by cehbrecht** [roocs/clisops#1]
* clisops version:
* Python version:
* Operating System:

### Description

Can we make an initial release 0.1.0 of the current clisops? This can be referenced by daops. After that we can merge the initial xclim subset module ... and make it a 0.2.0 release.

**Comment by agstephens** [comment]
@cehbrecht , I'm happy with that. Do you need input from myself or @ellesmith88 ?

**Comment by cehbrecht** [comment]
@agstephens I probably need more permissions on this repo.

**Comment by cehbrecht** [comment]
@agstephens Is it ok to add a new xclim-testdata repo to roocs? I can make then the first pull-request with the xclim subset ...

**Comment by ellesmith88** [comment]
@cehbrecht I've added you as an admin now so you should have all the permissions.

**Comment by cehbrecht** [comment]
done.
