### ISSUE TITLE
Enable macos and windows tests

### ISSUE THREAD

**Issue by cehbrecht** [roocs/clisops#10]
* clisops version:
* Python version:
* Operating System:

### Description

... test on windows and macos are currently disabled in `.travis.yml` (#8).

**Comment by Zeitsperre** [comment]
FYI, you may have a lot of trouble configuring the Windows build to work from vanilla Python. It relies on a lot of C-libraries/DLLs that are buggy to configure. I wouldn't attempt this unless I were someone familiar with Powershell and/or GitBash on Windows systems.

As an alternative, something I've considered doing for xclim is to build the Windows environment with Anaconda. This would be a much simpler approach. 

For the MacOS build, I can lend my assistance.

**Comment by cehbrecht** [comment]
@Zeitsperre For our project we only need clisops on unix machines. So, testing with python and anaconda is sufficient. But clisops should become a dependency of xclim ... to use the `subsetting`. We would follow your xclim requirements.

**Comment by Zeitsperre** [comment]
The funny thing is that the subset utilities are what adds a bunch of helper libraries to xclim. Part of the gains of migrating the subset tools here is we reduce the number of dependencies on xclim by nearly half!

**Comment by Zeitsperre** [comment]
In any case, I should be pushing a fix to the xclim library's Windows build this week. When that's approved, I'll migrate the configuration to this project as well.
