### ISSUE TITLE
Patch release after merging #100 and #101?

### ISSUE THREAD

**Issue by Zeitsperre** [roocs/clisops#102]
@huard and I were wondering if it would be possible to tag a patch release after integrating #100 and #101? It would be incredibly helpful in advancing some work in https://github.com/bird-house/finch.

**Comment by agstephens** [comment]
@ellesmith88: please incorporate PR #103 into the next release.

**Comment by ellesmith88** [comment]
@Zeitsperre @huard Yes - I'll do this

**Comment by ellesmith88** [comment]
v0.5.1 release

**Comment by huard** [comment]
Thanks !
