### ISSUE TITLE
Use getfile() caching for mini-esgf data tests

### ISSUE THREAD

**Issue by jhaigh0** [roocs/clisops#107]
### Description

* get all individual file paths from:
  * https://github.com/roocs/mini-esgf-data/tree/master/test_data/badc/cmip5/data/cmip5/output1/****/zostoga
* for each file:
  * call get_file(filepath, github_url=...mini-esgf-data)
* set the variables used by the tests to be the common base of the files with "*.nc" at the end.

**Comment by Zeitsperre** [comment]
@jhaigh0 feel free to make use of `query_folder` from an Ipython instance if you just want to list out all the URLs without having to manually copy-paste (just be sure not to commit a call that uses it to the testing suite).

**Comment by agstephens** [comment]
@jhaigh0 The other thing we need in our use of `get_file` is to change the `cache_dir` argument (for all paths that use the mini-esgf-data repo). We should set it as follows:

```
from pathlib import Path
mini_esgf_cache_dir = Path.home() / ".mini-esgf-data"
test_file = get_file(
    'test_data/badc/cmip5/data/cmip5/output1/MOHC/HadGEM2-ES/rcp85/mon/atmos/Amon/r1i1p1/latest/tas/tas_Amon_HadGEM2-ES_rcp85_r1i1p1_200512-203011.nc', 
    github_url='https://github.com/roocs/mini-esgf-data', 
    branch='master', 
    cache_dir=mini_esgf_cache_dir)
```

That will write the test files under: `~/.mini-esgf-data` which is what we want.

**Comment by jhaigh0** [comment]
Thanks @agstephens I've added that now

**Comment by agstephens** [comment]
In order to get all the tests running with the new file-caching approach, try doing:

```
mv -f tests/mini-esgf-data tests/mini-esgf-data.OLD
python -m pytest tests
```

This will _break_ the link to the old local submodule of mini-esgf-data, and show up any tests that are still using it.

I think the modules you need to fix are:

```
tests/ops/test_xarray_mean.py
tests/test_file_namers.py
```

Thanks

**Comment by agstephens** [comment]
We have changed the approach to a single `git clone` - and it works.
