### ISSUE TITLE
Hidden os.system call to shell git clone is dangerous/inconsistent

### ISSUE THREAD

**Issue by Zeitsperre** [roocs/clisops#121]
While trying to refresh my PR I came across the current method for collecting some of the testdata:
https://github.com/roocs/clisops/blob/de42bcadbf40789b57505308f67d48aefaf422eb/tests/conftest.py#L291

Unfortunately, there are some problems with this approach:
1. Changes to the repo upstream are not updated to the local folder if it already exists. This was causing issues when the `mini-esgf-data` upstream had files that weren't downloaded the last time `pytest` ran.
2. Using an `os.system` call is [dangerous](https://www.kevinlondon.com/2015/07/26/dangerous-python-functions.html) and the fact that it's hidden away in a testing configuration file isn't great either 
    * There are also better approaches for cloning a repo from python: https://gitpython.readthedocs.io/en/stable/reference.html#git.repo.base.Repo.clone_from.

I can lend a hand in configuring a fix for this. Just let me know.

**Comment by agstephens** [comment]
Hi @Zeitsperre, thanks for pointing these out. Regarding the two issues:
1. Do you have suggestions for keeping the tests up-to-date? My thoughts are:
   - force a update of the repo from github whenever pytest is run
   - use an environment variable to allow developers to override this behaviour, e.g.: `if os.environ.get('ROOCS_USE_CACHE_TEST_REPOS') == 'TRUE': ...do not update the repo(s)`
2. Yes, we can fix this issue - shouldn't be hard to do.

**Comment by Zeitsperre** [comment]
Hey @agstephens, for convenience, I would probably lean towards the forced update on run of `pytest`. The danger with that is if the local copy is on a different branch or an upstream change destroyed data. Could cause problems for local debugging. The `env_var` approach is much safer. You can also specify the branch and use `gitpython` to check it out if it's different from `main`/`master`.

If `git-lfs` wasn't such a pain to work with, that would be an interesting solution to version-control for testdata, but my experience with it was never great. [`intake`](https://www.anaconda.com/blog/intake-taking-the-pain-out-of-data-access) is another really clean and modern way of accessing data, but it needs to be hosted/published somewhere (likely outside of GitHub). Does your team have a public-facing THREDDS server?

**Comment by agstephens** [comment]
Thanks @Zeitsperre, 
Yes, we have a THREDDS server. But I think I would prefer the test data to be in Git, for its global accessibility - and also to avoid having to maintain it in a THREDDS/Intake catalog. 
We will implement the above issues regarding the `env_var` and `gitpython`.

**Comment by Zeitsperre** [comment]
Closed with #130
