### ISSUE TITLE
Modernize requirements and leverage pre-commit

### ISSUE THREAD

**Issue by Zeitsperre** [roocs/clisops#13]
This is an issue to identify a few problems:
- requirements_dev.txt is pinning several outdated python libraries (e.g. bumpversion 0.5.3 was released in 2015).
- Much of the travis and tox configurations borrowed from xclim are not used but not fully commented out from the configurations.
- `pre-commit`, a library that has made standardized development of xclim a breeze is not implemented here. This library automatically catches PEP8 and black errors before they are committed to the shared code base with almost no effort or extra steps needed from the contributor. For more information: https://pre-commit.com/.

I would like to contribute a fix for these issues.

**Comment by agstephens** [comment]
Hi @Zeitsperre , that's great. we welcome your fixes. 👍
