### ISSUE TITLE
New cf_xarray breaks clisops

### ISSUE THREAD

**Issue by aulemahal** [roocs/clisops#139]
* clisops version: branch fix-137
* Python version: all
* Operating System: github actions

### Description
As can be seen in the builds of #138, many tests are now failing with `cf_xarray` errors. The new version 0.5.0 came out today.

**Comment by aulemahal** [comment]
Oh just realized that it breaks `roocs-utils`, not clisops specifically.

**Comment by aulemahal** [comment]
Second edit : the problem is in `cf_xarray`,  xarray-contrib/cf-xarray#179 .

**Comment by dcherian** [comment]
Can you set up an upstream-dev CI environment to catch these regressions?

**Comment by aulemahal** [comment]
@dcherian  That's a good suggestion!

@agstephens  @ellesmith88 testing clisops or roocs-util against cf_xarray@master could be a nice option, if action minutes allow it.

**Comment by aulemahal** [comment]
The issue is now fixed in cf_xarray. Another small issue related to the new cf_xarray was also fixed in #138.

**Comment by ellesmith88** [comment]
Thanks for sorting @aulemahal, I've opened an issue in `roocs-utils` (https://github.com/roocs/roocs-utils/issues/60), would make most sense to do it there.
