### ISSUE TITLE
Make a patch release for xarray 0.18 support

### ISSUE THREAD

**Issue by Zeitsperre** [roocs/clisops#171]
With the newest version of xarray, CLISOPS v0.6.3 is broken. The fix is already in master and was just wondering if we could get a 0.6.4 if there's time for it this week?

Thanks again!

**Comment by agstephens** [comment]
Hi @Zeitsperre, Thanks for drawing this to our attention. Unfortunately, we have two members of the team away this week and I am snowed under with proposals and admin. I will ask @ellesmith88 to prioritise this next week when she is back.

**Comment by ellesmith88** [comment]
@Zeitsperre v0.6.4 out on pypi, conda package coming later today

**Comment by Zeitsperre** [comment]
Thanks a bunch!
