### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by Zeitsperre** [roocs/clisops#175]
Hey ROOCS team, I was wondering if `clisops` follows a release schedule of sorts? We are hoping to integrate the newest additions (#174) to our PAVICS stack and were wondering when releases are typically tagged (patch release every month?)

Thanks again and all the best!

**Comment by Zeitsperre** [comment]
@aulemahal

**Comment by ellesmith88** [comment]
Hi @Zeitsperre, we don't really have a release schedule, we're just doing it as and when its needed for our project and for your work. We think we'd probably struggle to stick to any kind of schedule, especially in the coming months as I will be doing a placement elsewhere.

We're happy to do it whenever you want. So if you need a release, if you open an issue and assign/tag me and @agstephens (to make sure someone sees it), then we'll be happy to do it 😄

**Comment by Zeitsperre** [comment]
That would be great! Thanks!
