### ISSUE TITLE
Suggested approach for default grid when regridding (C3S approach)

### ISSUE THREAD

**Issue by agstephens** [roocs/clisops#181]
* clisops version: *
* Python version: *
* Operating System: *

### Description

The C3S Team have provided the following suggestion on the default grid when regridding:

> Ideally the default target grid would use an adaptive resolution based on the resolution of the input data, in the same way as the `ct.geo.marke_regular` service in the CDS Toolbox. The method can be summarised by the following code snippet, where `xinc` and `yinc` are the lon/lat resolution of the target grid:

```
    xsize = data[x].size

    ysize = data[y].size

    xfirst = data.lon.values.min()

    yfirst = data.lat.values.min()

    xlast = data.lon.values.max()

    ylast = data.lat.values.max()

    xinc = (xlast - xfirst) / (xsize - 1)

    yinc = (ylast - yfirst) / (ysize - 1)
```

**Comment by sol1105** [comment]
From our discussion:
- that method can be a special case of the grid_instructor (eg. when specifying an empty tuple), or of the grid_id (eg. "auto")
- a check will be needed that tests if source and target grid are the same

**Comment by sol1105** [comment]
This is already included since https://github.com/roocs/clisops/pull/243
