### ISSUE TITLE
Add pytest marker(s) for regridding (to include/exclude) tests

### ISSUE THREAD

**Issue by agstephens** [roocs/clisops#182]
* clisops version: * 
* Python version: * 
* Operating System: *

### Description

Could use pytest markers for dealing with tests that use xesmf. Maybe it would look like:

* At top of module:
  ```
  import pytest
  pytestmark = pytest.mark.regrid
  ```
  See: https://docs.pytest.org/en/6.2.x/example/markers.html#marking-whole-classes-or-modules
* Then the test rules could be:
  * pyXY: `python -m pytest -m "not regrid" tests`
  * conda-xesmf: `python -m pytest tests` (i.e. all)

This approach would avoid needing to individually add decorators...but, running locally would require remembering whether to run with the tag, or not...???

**Comment by sol1105** [comment]
@agstephens Is this still relevant?

At the moment we use in the module
```python
# Try importing xesmf and set to None if not found at correct version
# If set to None, the `require_module` decorator will throw an exception
XESMF_MINIMUM_VERSION = "0.6.2"
try:
    import xesmf as xe

    if parse_version(xe.__version__) < parse_version(XESMF_MINIMUM_VERSION):
        raise ValueError()
except Exception:
    xe = None
```
and in the tests
```python
from clisops.core.regrid import XESMF_MINIMUM_VERSION, xe

XESMF_IMPORT_MSG = (
    f"xESMF >= {XESMF_MINIMUM_VERSION} is needed for regridding functionalities."
)


@pytest.mark.skipif(xe is None, reason=XESMF_IMPORT_MSG)
def test123():
  [...]
```

**Comment by agstephens** [comment]
Hi @sol1105 , I will close this. Thanks
