### ISSUE TITLE
clisops __version__ not found

### ISSUE THREAD

**Issue by Zeitsperre** [roocs/clisops#19]
Noticed this error occurring on the ReadTheDocs build. While `__init__.py` isn't needed for packages in Python3, it's terribly convenient when it comes to ensuring that the version of the library is available when imported. My suggestion would be to simply add a single `__init__.py` at the top-level of the library or to add a `__version__` object to the main module to set the version. 

This would ultimately be managed by bumpversion.

**Comment by cehbrecht** [comment]
fixed by PR #20
