### ISSUE TITLE
Review the regrid-main branch ready for merger

### ISSUE THREAD

**Issue by agstephens** [roocs/clisops#215]
## Description

@sol1105 and @ellesmith88: in preparation for merging the `regrid-main` branch into the clisops `master` branch, I am asking @ellesmith88 to review the existing code that @sol1105 has written. The main aims for doing this are:
1. Ensure that the structure of the new `regrid` code is in line with the existing subset
2. Place the constants, functions and classes into the `clisops.utils`, `clisops.ops` and `clisops.core` packages following existing practices.
3. Ensure that names for modules, functions, classes and methods follow existing practices.
4. Ensure that the appropriate level of documentation exists in docstrings (for modules and functions/methods).
5. Ensure that the unit test coverage is suitable.
6. Develop the Jupyter Notebooks to demonstrate the functionality.
7. Consider the `daops` interface that will sit on top of the `clisops` interface.

## Proposed approach

Please create a new branch (or multiple branches) to develop the modified version of the code.

**Comment by ellesmith88** [comment]
Martin asked me to focus on points 1 and 3 and the notebook initially while he continues working on the rest. I have added comments to the PR from ``regrid-main-martin`` to ``regrid-main``.

I can look at points 2, 4 and 5 next. The daops interface already exists https://github.com/roocs/daops/blob/regrid-main/daops/ops/regrid.py but probably needs to be updated.
