### ISSUE TITLE
Encountering problem with `clisops.ops.subset` related to `clisops.utils.dataset_utils.check_lon_alignment`

### ISSUE THREAD

**Issue by sol1105** [roocs/clisops#217]
* clisops version: latest

### Description

The problem is related to the Issue #35 / PR #117. The function `check_lon_alignment` in `clisops.utils.dataset_utils` converts the longitude coordinate of a dataset between the two longitude frames `[0, 360]` and `[-180, 180]`, depending on the longitude interval selected for the subset operation. When I tested it (see below), the longitude bounds, unlike the longitude axis itself, were not converted.

### What I Did

In the following example, the longitude values are converted to the `[-180, 180]` frame and a roll is performed (internally by `check_lon_alignment`) before the actual subset  operation is performed. After completion, the `lon_bounds` however are still in the old longitude frame `[0, 360]`:

```python
import xarray as xr
import clisops.ops as clops
import cf_xarray as cfxr

ds = xr.tutorial.open_dataset('air_temperature')

# Create bounds
dsb = ds.cf.add_bounds("lon")
dsb = dsb.cf.add_bounds("lat")
print(repr(dsb))
print("-"*30)

# ops subset - bounds become incorrect
outputs = clops.subset(
        ds=dsb,
        area=(-120, 20, -150, 70),
        output_type="xarray",
    )
print(repr(outputs[0]))
```
* Before: 
```
   lon         200.0 202.5 205.0 207.5 ... 325.0 327.5 330.0
   lon_bounds  198.8 201.2 203.8 ... 326.2 328.8 331.2
```
* After:
```
  lon          -150.0 -147.5 -145.0 ... -125.0 -122.5 -120.0
  lon_bounds   208.8 211.2 213.8 ... 236.2 238.8 241.2
```

In contrast to that, the wrapper function `check_lons` in `clisops.core.subset` adjusts the longitude selection interval to the longitude frame of the dataset (which however has the disadvantage that the case of crossing the 0-meridian is not always defined):
```python
# core subset - bounds correct
from clisops.core import subset
ds_out=subset.subset_bbox(dsb, lat_bnds=[20, 70], lon_bnds=[-150, -120])
print(repr(ds_out))
```
* Results in:
```
  lon          210.0 212.5 215.0 217.5 ... 235.0 237.5 240.0
  lon_bounds   208.8 211.2 213.8 ... 236.2 238.8 241.2
```

### Suggestion

I suggest to adjust `check_lon_alignment` in the following way, which should also allow the conversion between the two longitude frames `[0, 360]` / `[-180, 180]` for curvilinear grids (i.e. 2D coordinate variables):
* if conversion is necessary:
    *  if in frame [-180, 180], add 360 to lon and lon_bnds for values < 0
    *  if in frame [0, 360], subtract 360 from lon and lon_bnds for values > 180
* after conversion, instead of a `roll`, perform a `sortby(lon dimension)` to ensure the data can subsetted:
     * rectilinear case (1D coordinate vars): `ds.sortby(lon)`
     * curvilinear case (2D coordinate vars): 
          * overwrite the longitude index with any of the rows of the 2D longitude coordinate variable, eg.  `ds.assign_coords({"x":ds["lon"][0,:].squeeze().values})` with `x` being the lon dimension
          * now perform the `ds.sortby(x)` 

What are your thoughts regarding this? In the unlikely case I did not overlook anything, the execution of this function could be moved from `ops` to `core`, so `clisops.core.subset.check_lons` is no more necessary (or at least the crossing 0-meridian case is dealt with, which is not implemented there atm).

**Comment by ellesmith88** [comment]
Hi @sol1105 , have you managed to get this working? I'm not sure it is as simple as adding/subtracting 360. I think this is the method I had originally tried, which ending up not working (see https://github.com/roocs/clisops/issues/127 and related fix https://github.com/roocs/clisops/pull/129/files). There are also a few cases where the longitude is defined as -270 to 90 I believe, so there isn't only the 2 frames you have mentioned above.

Also, I think this section of ``clisops.utils.dataset_utils.check_lon_alignment`` https://github.com/roocs/clisops/blob/d7c3d7ad9224618a79622bd26125a7dcd7e5c8d0/clisops/utils/dataset_utils.py#L80-L84 alters the coordinate values so they are monotonically increasing/decreasing.

**Comment by sol1105** [comment]
Hi @ellesmith88, it is indeed not as easy as I had hoped at first. I struggled a little but I have my hopes up now the function does what I want of it. Ags example from #127 is working. I will add a few tests now to be more certain, and then create a PR so you can have a look. The shifted longitude frames (eg. -270,90) are what I need this kind of function for in regridding, since xesmf does not accept that as input (and nor should the ESGF have done :slightly_smiling_face: ).
