### ISSUE TITLE
Get clisops ready for acceptance by Xclim

### ISSUE THREAD

**Issue by agstephens** [roocs/clisops#23]
Tag as version 3 and make a  pull request to Xclim.

**Comment by Zeitsperre** [comment]
What would be needed on the xclim side exactly?

**Comment by cehbrecht** [comment]
> What would be needed on the xclim side exactly?

... I will make a PR to xclim. It will remove the subset package. `clisops` will only be used by the notebook examples in xclim ... so the PR will update the examples as well.

**Comment by cehbrecht** [comment]
see #31
