### ISSUE TITLE
Determine chunk size instead of using dask config

### ISSUE THREAD

**Issue by ellesmith88** [roocs/clisops#54]
### Description
we need something here that finds `nbytes` and `n_time_steps` and uses our config memory limit in "clisops:read" to decide on a sensible chunk_length
```
    var_id = get_main_variable(ds)
    da = ds[var_id].chunk({'time': chunk_length})
    da.unify_chunks()
    ds.to_netcdf(tmp_file)
```

Also set environment variables in `roocs_utils/etc/roocs.ini ` and set in `clisops/__init__.py`

```
print('[WARNING] Heeding warning about Dask environment variables: https://docs.dask.org/en/latest/array-best-practices.html#avoid-oversub
scribing-threads')
print("""export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
""")
for key in 'OMP_NUM_THREADS MKL_NUM_THREADS OPENBLAS_NUM_THREADS'.split():
    os.environ[key] = '1'
```

**Comment by agstephens** [comment]
In the tests, you could try using info from:

https://docs.dask.org/en/latest/configuration.html#environment-variables

e.g.:

`export DASK_ARRAY__CHUNK_SIZE=100MiB`

and:

https://docs.dask.org/en/latest/configuration.html#refreshing-configuration

e.g.:

`dask.config.refresh()` - which might pick up the config changes based on what you have changed.

```
def test...():


      chunk_memory_limit = '50MiB'
      os.environ['DASK_ARRAY__CHUNK_SIZE'] = chunk_memory_limit 
      dask.config.refresh()

      assert dask.config.get('array.chunk-size') == chunk_memory_limit 

      do...test...

      ...tidy up here by reverting the dask setting to its original value
```

**Comment by agstephens** [comment]
Implemented.
