### ISSUE TITLE
Implement subset by level

### ISSUE THREAD

**Issue by agstephens** [roocs/clisops#58]
Discuss with Ouranos how we should implement this. Maybe inside `clisops.core.subset`.

**Comment by agstephens** [comment]
@Zeitsperre: yes, we are talking about the "z" axis. Let's discuss when we meet how to set this up in `clisops.core.subset.`

I am hoping that the Xarray/Dask lazy evaluation means that we can chain a `subset_level` function with the other existing functions rather than modifying what already works.

**Comment by agstephens** [comment]
I think that we should consider this in the same way `subset_time` is addressed within the `subset_bbox` function:

https://github.com/roocs/clisops/blob/999a34fee79af216fdeb6cf6969199dfd1e42944/clisops/core/subset.py#L650

`subset_bbox` has the optional arguments `start_date` and `end_date`, at the end of the function there is optionally a call to `subset_time`. 

We could imagine that the 'z' axis could be handled in the same way, by adding (and integrating) the following:

```
def subset_level(ds, start_level, end_level)
```

This would need to:
 - check available levels overlap with the level range provided
 - reverse the start_level and end_level if they are ordered differently to the values in the level axis - this is reasonable because the user may not know how the file is structured
 - select the data within the level range provided

**Comment by Zeitsperre** [comment]
I realize that the number of existing decorators is getting a bit unwieldy but given that checks exist for X and Y dims, the best option I would suggest for the `start_level` and `end_level` checks would be to write a `check_levels` decorator (or expand the `check_lons` as I mentioned in #65) to be able to add this easily to other subsetting functions.

If a function is written to perform the Z-axis subsetting, it can be added to all other subsetting functions, as needed. In-depth level check could be added to either function or the decorator, I imagine.

With all these different functions, it would be interesting to consider alternative means of calling these functions down-the-line Perhaps something to consider if `clisops` proceeds with #37.

**Comment by agstephens** [comment]
Now merged into master.
