### ISSUE TITLE
Are we doing ".compute()" correctly on delayed dask object?

### ISSUE THREAD

**Issue by agstephens** [roocs/clisops#61]
@ellesmith88: I was just comparing the documentation on the dask pages with our implementation at:

http://xarray.pydata.org/en/stable/dask.html

Their example is:

```
delayed_obj = ds.to_netcdf("manipulated-example-data.nc", compute=False)
results = delayed_obj.compute()
```

Our code is:

```
        with dask.config.set(scheduler="synchronous"):
            chunked_ds.to_netcdf(output_path, compute=False)
            chunked_ds.compute()
```

I think our code should be:

```
        with dask.config.set(scheduler="synchronous"):
            delayed_obj = chunked_ds.to_netcdf(output_path, compute=False)
            delayed_obj.compute()
```

Please check which is the correct implementation. Remembering that `compute=False` was writing files but filling them with empty arrays. Thanks

**Comment by ellesmith88** [comment]
@agstephens - You're right - no wonder the memory usage was so small for the tests I did on this.
Having tested that method properly I found that the memory usage is still changed when the memory limit changes - but the method:
```
ds = xr.open_mfdataset("files/*.nc", use_cftime=True, combine='by_coords')

chunk_length = get_chunk_length(ds, mem_limit)
chunked_ds = xr.open_mfdataset("files/*.nc", use_cftime=True, combine='by_coords', chunks={"time": chunk_length})

with dask.config.set(scheduler="synchronous"):
   delayed_obj = chunked_ds.to_netcdf('test.nc', compute=False)
   delayed_obj.compute()
```
uses less memory e.g. (75.5MiB compared to 473.6 MiB). However it doesn't vary with the memory limit we set.

**Comment by ellesmith88** [comment]
We have decided to not include the extra line `chunked_ds = xr.open_mfdataset("files/*.nc", use_cftime=True, combine='by_coords', chunks={"time": chunk_length})` as it is messier and we hope that the discrepancy between chunking when opening the dataset and chunking afterwards will be resolved by the developers.

**Comment by agstephens** [comment]
Working in production.
