### ISSUE TITLE
Share Notebooks

### ISSUE THREAD

**Issue by agstephens** [roocs/clisops#64]
with Ag and Elle

**Comment by sol1105** [comment]
@agstephens @ellesmith88 The Notebooks can be accessed via our "Regridding" GoogleDrive: 
https://drive.google.com/drive/folders/1cuBHbYaUH5fy1PisUtZc4Lvbca6bzZS8

Please, if you do not have access yet, send me your Google-User-ID via Slack

I added a few plots for the differences between the regridded fields to the xESMF_Test Notebook. For this case (MPI-ESM-HR regridded to MPI-ESM-LR) most "problematic" seem to be the areas of central Africa and the northern Atlantic ocean.
Furthermore I added my current "recipe" to set up a conda environment with xESMF and clisops, which will be hopefully reduced to an environment.yml in the future.

**Comment by agstephens** [comment]
Thanks @sol1105 , that's awesome. I'll close this issue 👍
