### ISSUE TITLE
fix black style check complains

### ISSUE THREAD

**Issue by cehbrecht** [roocs/clisops#7]
* clisops version:
* Python version:
* Operating System:

### Description

[black](https://pypi.org/project/black/) style checks tests are run by travis. Fix complains.

**Comment by Zeitsperre** [comment]
@cehbrecht Can you allow me push access. I've fixed this in a branch I have locally.

**Comment by cehbrecht** [comment]
@Zeitsperre I have send you an invitation as team member. But you can make a PR.
