### ISSUE TITLE
Add a Pull Request template for CLISOPS

### ISSUE THREAD

**Issue by Zeitsperre** [roocs/clisops#70]
PRs could benefit from a template of questions that the contributor could answer. Some identifiers like "What does this PR change?" and "Are there breaking changes?" are things I've seen across GitHub and xclim has a few as well. I can add that at some point soon.

**Comment by agstephens** [comment]
Thanks @Zeitsperre. This will be great. (By the way, I'm loving pre_commit - can't believe I've not been aware of it).

**Comment by Zeitsperre** [comment]
@agstephens Glad to hear it! It really changed things up quite a bit when it was introduced in `xclim`. The number of PEP8-fixing commits dropped near zero. There are quite a few hooks available as well. Really neat development tool, for sure.
