### ISSUE TITLE
Can we move the "notebooks" directory to the top-level (and link to it in the "docs" directory)

### ISSUE THREAD

**Issue by agstephens** [roocs/clisops#76]
Hi @huard @Zeitsperre as part of getting ready for our first formal release of `clisops` we would to:

1. Move `<repo>/docs/notebooks` to `<repo>/notebooks`
2. Symlink `<repo>/docs/notebooks` to `<repo>/notebooks`
3. Add a new notebook for our top-level `clisops.ops.subset` module and connect it to the sphinx documentation.

Are you happy for us to do this?

**Comment by Zeitsperre** [comment]
Sounds fine to me!

**Comment by agstephens** [comment]
Thanks, we'll do it!
