### ISSUE TITLE
Images in notebooks in docs not showing

### ISSUE THREAD

**Issue by ellesmith88** [roocs/clisops#85]
The images in the Subsetting Utilities notebooks in the documentation are not showing. This might be something the do with the path/ symlink between the two notebook directories.

**Comment by cehbrecht** [comment]
maybe a library is missing in the docs requirements `docs/environment.yml` ... for example `matplotlib`:
https://github.com/Ouranosinc/xclim/blob/68199220d2430a49e4f97b951ee38be319ab7c35/setup.py#L42

**Comment by Zeitsperre** [comment]
I would consider adding it to a docs_requirements recipe so that the build environment doesn't get bogged down with lots of requirements used only in Jupyter notebooks.

**Comment by ellesmith88** [comment]
`matplotlib` is included in the docs requirements in `setup.py`: 
https://github.com/roocs/clisops/blob/master/setup.py#L27-L35 and I think I've included these requirements in the build for the docs through `.readthedocs.yml`: https://github.com/roocs/clisops/blob/master/.readthedocs.yml#L22-L28. Have I missed something here?

If this is right I imagine that means I could take some requirements out of `docs/environment.yml` or get rid of it all together?

I have saved the notebook with its outputs which might contribute to the problem, but when saving it with no outputs it doesn't execute in the docs - even though I have `nbsphinx_execute = "auto"` in `docs/conf.py`

**Comment by cehbrecht** [comment]
I would remove all outputs from the notebooks (unless it is intended to be there). Personally I would add the docs requirements to the conda `docs/environment.yml` and skip it in `setup.py` ... or they other way around but not mixed.

There are warnings in the RTD build:
https://readthedocs.org/api/v2/build/12314018.txt

> /home/docs/checkouts/readthedocs.org/user_builds/clisops/checkouts/static_typing_fix/docs/notebooks/core_subset.ipynb:: WARNING: image file not readable: notebooks/../_build/doctrees/nbsphinx/notebooks_core_subset_3_1.png

**Comment by Zeitsperre** [comment]
closed with #100
