### ISSUE TITLE
some clisops.subset tests are failing with tox ...

### ISSUE THREAD

**Issue by cehbrecht** [roocs/clisops#9]
* clisops version:
* Python version:
* Operating System:

### Description

I have marked in PR #8 some subset tests with `pytest.xfail` which are failing in a tox environment but are working with a conda environment.

**Comment by cehbrecht** [comment]
Marked xfail test:
https://github.com/roocs/clisops/blob/c8de62ee23ea58219c08c5f3d58b0227da90413f/tests/test_operations/test_subset.py#L630

Failing tests marked with xfail in python environment 3.6 on travis:
https://travis-ci.org/github/roocs/clisops/jobs/680592674

... but they all pass in a conda environment:
https://travis-ci.org/github/roocs/clisops/jobs/680592676

@zeitsperre @huard do you have an idea why this happens? Looks like a dependency issue. I tried with the same version on conda and python env ... but no success. It does not happen in xclim tests.

**Comment by Zeitsperre** [comment]
Saving issue to look at  next week.

**Comment by Zeitsperre** [comment]
@cehbrecht Is this still an issue?

**Comment by cehbrecht** [comment]
@Zeitsperre it is still an issue. The tests are now in `tests/core/test_subset.py` and marked with xfail:
https://github.com/roocs/clisops/blob/dc731d4fe23ce1abc04dd566cf6bca90b187dec8/tests/core/test_subset.py#L630

You can see it in the latest travis ci build. Python fails (xfail):
https://travis-ci.org/github/roocs/clisops/jobs/691262738

... while with conda all tests pass (xpass):
https://travis-ci.org/github/roocs/clisops/jobs/691262742

**Comment by Zeitsperre** [comment]
Interesting. I honestly surprised that they pass, given that the code to handle the splitting of polygons and reprojecting isn't present. I'll look into this tomorrow but honestly, I think it should all be failing.

The only thing I can think of is that conda is installing the base C-libraries for some functions being called (like PROJ) that only are needed for this specific cases. If they aren't there, then surely that is what's causing the failures in pure Python builds.
