### ISSUE TITLE
irregular grids not being subsetted correctly

### ISSUE THREAD

**Issue by ellesmith88** [roocs/clisops#92]
* clisops version: 0.4.0
* Python version:
* Operating System:

### Description

I was testing subsetting on some irregular grids - in one example the dimensions were `time`, `i` and `j` and in another `time`, `rlat`, `rlon` and found that latitude and longitude weren't being subsetted correctly. e.g. in one case `latitude` was subsetted as expected but for `longitude` the min and max values changed by a few decimal places but stayed around 0 and 360. I narrowed it down to these few lines in `subset_bbox`: 

https://github.com/roocs/clisops/blob/a3236f55b6d48bf3aedbae092d48e5ed2808c1c1/clisops/core/subset.py#L756-L764

But I couldn't work out what was going wrong. 

Tagging @Zeitsperre

**Comment by Zeitsperre** [comment]
Ping @tlogan2000

**Comment by tlogan2000** [comment]
@Zeitsperre possible to provide a problematic file to check this?  I believe this issue is related to having files with descending order coordinates and the subsequent `slice(coords.min().values, coords.max().values) ` does not find any values in the range.

possible fixes to explore:

- [ ] apply the slice using first and last element (i.e. not min max) `slice(coords[0].values, coords[-1].values) 

- [ ] apply a `da.sortby()`  before slicing ( might be long on large datasets?) 

- [ ]  check to see if coords are in descending order : if True applying a reverse slice  `slice(coords.max().values, coords.min().values) `

**Comment by Zeitsperre** [comment]
Assigning this to myself and @tlogan2000 I'm experiencing similar problems in my PR #91 so the fix should be put forward in there.

**Comment by ellesmith88** [comment]
I've added the dataset I was looking at as a test dataset in `mini-esgf-data`: https://github.com/roocs/mini-esgf-data/blob/master/test_data/gws/nopw/j04/cp4cds1_vol1/data/c3s-cmip5/output1/NCC/NorESM1-ME/rcp60/mon/seaIce/OImon/r1i1p1/tsice/v20120614/tsice_OImon_NorESM1-ME_rcp60_r1i1p1_200601-205012.nc

The case mentioned above where latitude seemed to be subsetted correctly but longitude wasn't was using this dataset and the test was:

```
from clisops.ops.subset import subset
import xarray as xr

def test_coord_variables_subsetted_i_j():
    """
    check coord variables e.g. lat/lon when original data
    is on an irregular grid are subsetted correctly in output dataset
    """

    ds = xr.open_mfdataset(C3S_CMIP5_TSICE)

    assert "lat" in ds.coords
    assert "lon" in ds.coords
    assert "i" in ds.dims
    assert "j" in ds.dims

    area = (5.0, 10.0, 20.0, 65.0)

    result = subset(
        ds=C3S_CMIP5_TSICE,
        time=("2005-01-01T00:00:00", "2020-12-30T00:00:00"),
        area=area,
        output_type="xarray",
    )
```

after which I compared the maximum and minimum of the latitude and longitude of the subsetted dataset with the values I would expect from `area`. 

However, I'm not sure this test will be very informative with the test data where I have selected every 45th `i` and `j`. I will have another look at this

**Comment by agstephens** [comment]
Thanks for picking this up @ellesmith88

**Comment by ellesmith88** [comment]
@Zeitsperre @tlogan2000 
I tried the same test with the test dataset on a branch (`subset_irregular_grid`).

I've added the test dataset here:
https://github.com/roocs/clisops/blob/e0781dd81a31ac058711f662cb2c660a7e882628/tests/_common.py#L116-L119

This is the test that I've been looking at:
https://github.com/roocs/clisops/blob/e0781dd81a31ac058711f662cb2c660a7e882628/tests/ops/test_subset.py#L553-L580

With this example I'm subsetting with longitude bounds of (10.0, 350.0) but the minimum and maximum longitude values of the output dataset are 9.177159 and 358.5246

For the same test looking at latitude - I've used bounds of (10.0, 65.0) but the output dataset has minimum and maximum latitude values of 10.078998 and 84.334114.

This is using `clisops.ops.subset.subset` which calls `clisops.core.subset.subset.bbox`. I have to say that I don't fully understand how the subsetting works in the case where the dataset doesn't have a regular lat/lon grid, but I would have thought the max/min longitude and latitudes of the output dataset should be within the bounds?

**Comment by tlogan2000** [comment]
> I would have thought the max/min longitude and latitudes of the output dataset should be within the bounds?

@ellesmith88 I think for the irregular case we will have to check max/ min values with the addtional requirement of only checking gridcells that are `notnull()`  ... The subset output retains its rectangular grid in the rotated rlon, rlat dimensions and can therefore potentially include actual lons and lats outside the bbox bounds but they should all end up being masked as nans in the actual temperature / precip data

**Comment by ellesmith88** [comment]
@tlogan2000 I see, thank you. In which case this isn't a bug at all, just me not understanding what's going on. I've had a play around with the data now and can see the output is as expected, so I'll update my tests and this can be closed. Thanks again!
