### ISSUE TITLE
subset_shape excludes points lying on the polygon boundary

### ISSUE THREAD

**Issue by huard** [roocs/clisops#99]
* clisops version: 0.5.0

### Description
In the original xclim version, `subset_shape` returned points whose centroid lies at the polygon boundary. In the current version, those points are excluded. Is this change desired ?

**Comment by aulemahal** [comment]
Just read some doc of shapely, looks like this behaviour was to be expected, but we didn't know it.
In shapely language, that geopandas follows, for a polygon p and a point P:
 - p "contains" P : if it is inside, but NOT on the boundaries,
 - p "touches" P : if it is on the boundaries,
 - p "intersects" P : if it is inside OR on the boundaries.

In the non-vectorized version of `create_mask`, we were using `gpd.tools.sjoin` with `op = 'intersects'`, resulting in the wanted behaviour. In the vectorized version, we are using `vectorized.contains`, thus the bug.

Sadly, `shapely.vectorized` doesn't implement `intersects`, but it does implement `touches`, so a 2-pass method could solve the problem.

**Comment by Zeitsperre** [comment]
Thanks for looking into this @aulemahal! I figured it must have been a `touches` issue, but It's great to have this clarified. It should be simple to fix (and perhaps this is something we want to have a case/test for?).

**Comment by Zeitsperre** [comment]
I've started work on this, but it still needs testing https://github.com/roocs/clisops/tree/vectorize_touching_poiints

**Comment by Zeitsperre** [comment]
fixed with #101
